services:
  - type: web
    name: towiz-renovaciones
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /healthz
    envVars:
      - key: WHATSAPP_NUMBER
        sync: false
      - key: PROMO_IMAGE_URL
        sync: false
      - key: LOGO_IMAGE_URL
        sync: false
